### ISSUE TITLE
Publish images in Cloudstate docker repository 

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/kotlin-support#19]
@viktorklang ping

**Comment by viktorklang** [comment]
@sleipnir Which images?

**Comment by sleipnir** [comment]
@viktorklang Shopping-cart images. I saw that people are using the images from my repository. Actually, I don't even know if this is interesting, I encouraged to do the build itself, but it is strange in the examples of the cloudstate repository that I am uploading images to other repositories.

**Comment by viktorklang** [comment]
We should repackage the TCK so that each different language support can run a TCK-based Docker build in their own project.

**Comment by ihostage** [comment]
I absolutely agree with @viktorklang

**Comment by sleipnir** [comment]
@viktorklang  will we follow that line that we had talked about then of the native TCK image? Cool, do you have any idea when this will happen?

But I think that this has nothing to do with the question I asked. But let's wait

**Comment by viktorklang** [comment]
@sleipnir The reason I mentioned it is because now cloudstate needs to pull in these images as well.

**Comment by sleipnir** [comment]
I know @viktorklang  I am following this movement closely as you well know.
But what I said is that there are people looking for the image of shopping-cart in the language they prefer. I don't know why they do it, I don't encourage it but they do it anyway. So what I basically said is: If people want to experiment based on the finished image of an example, maybe because their interest is in the kubernetes part, I don't know, so they should find these images on an official Cloudstate channel. I don't really care where the images are, but maybe that's interesting for the project itself and its visibility. I only opened this issue because of a user who came to me and I found it interesting to share this experience with you through this issue.
☺😝

**Comment by ihostage** [comment]
@sleipnir I right understand, that somebody can't locally build an image for examples and play with him?

**Comment by sleipnir** [comment]
@ihostage 
that's exactly what I said to those who asked me the same question (in another words of course). the point of the question is not the build I do it myself dozens of times a day locally in my own repository.
The point that I tried to make clear but maybe I didn't get is: some people want to play with a ready example image and for Lightbend / Cloudstate wouldn't it be interesting to serve this audience? Only that, as I said I don't really care where they are but I questioned @viktorklang if he doesn't want to serve this audience too. If he or the rest of the team doesn't want it for me, that's fine too

**Comment by sleipnir** [comment]
What I honestly think is that a few free public images in a Cloudstate docker hub repository won't do any harm

**Comment by sleipnir** [comment]
@ihostage I'm also not here to judge what some people can and can't do. I came across the issue and passed it on to the others to debate

**Comment by ihostage** [comment]
> What I honestly think is that a few free public images in a Cloudstate docker hub repository won't do any harm

I agree 😄 My question was only to correctly understand the motivation of this issue.

> @ihostage I'm also not here to judge what some people can and can't do. I came across the issue and passed it on to the others to debate

Sorry, maybe it was not good a word in my question. 🤷‍♂️ My "can't" was not about the possibility. It was about understanding the point of problem for users. And I thought, maybe we can resolve a problem by the more detailed documentation, for example.

**Comment by sleipnir** [comment]
No problems @ihostage . We will undoubtedly have better documentation at this point so that users know exactly how to get started and what they can achieve.

**Comment by sleipnir** [comment]
@ihostage I created a new issue to address the documentation issue as suggested. But the question remains of the images pending answer for another time here.
@viktorklang i appreciate comments

**Comment by viktorklang** [comment]
@sleipnir Having a library of "Community Examples" souds like an interesting idea. Adding my colleagues @kwehden and @pvlugter here

**Comment by kwehden** [comment]
We would absolutely welcome a set of community examples. perhaps conversion of some of our existing examples to kotlin. What did you have in mind in terms of features to highlight?

**Comment by sleipnir** [comment]
Hi @kwehden there are already some ready examples in the Kotlin repository. I think the question here was more about the ready-made images on Dockerhub of these running examples so that users can play fast with the support languages and have certain functional use cases to look at. I think that was it

**Comment by pvlugter** [comment]
We can certainly publish more samples to docker hub. Just let us know names of repositories to create. I'll also set up contributor teams with access to these cloudstateio repositories on docker hub — let me know docker hub usernames to add.

**Comment by sleipnir** [comment]
I think they are the same teams from the github repository. It would be nice to send this question to the group for everyone to see, or individually I don't know. My dockerhub email is sleipnir@bsd.com.br

**Comment by pvlugter** [comment]
@sleipnir, I've added you to kotlin, dart, and python teams in docker hub. Let me know docker repositories that need to be created.

**Comment by sleipnir** [comment]
Hello @pvlugter for now would be: 
dart -> dart-shoppingcart 
kotlin -> kotlin-shoppingcart, kotlin-chat, kotlin-pingpong
springboot -> springboot-shoppingcart, springboot-shoppingcart-jsr330
python -> python-shoppingcart

**Comment by pvlugter** [comment]
Since there's already some sample images published, I've used the same naming conventions. I've created these repositories:

```
cloudstateio/samples-dart-shopping-cart
cloudstateio/samples-kotlin-shopping-cart
cloudstateio/samples-kotlin-chat
cloudstateio/samples-kotlin-pingpong
cloudstateio/samples-springboot-shopping-cart
cloudstateio/samples-springboot-shopping-cart-jsr330
cloudstateio/samples-python-shopping-cart
```

**Comment by sleipnir** [comment]
Thanks @pvlugter
