### ISSUE TITLE
Protobuf build problems

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/kotlin-support#5]
Remove build issues related to the compilation and classpath of protobuf artifacts. 
Follow the discussion here:

https://github.com/cloudstateio/kotlin-support/pull/4#discussion_r386973118
https://github.com/cloudstateio/kotlin-support/pull/4#discussion_r386974404

**Comment by vkorenev** [comment]
Blocked by cloudstateio/cloudstate#285.
