### ISSUE TITLE
Deploy to Maven Centrail failure

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/kotlin-support#50]
When trying to deploy via travis the error below occurs:

```
* What went wrong:

Execution failed for task ':bintrayPublish'.

> Could not sync 'cloudstateio/releases/cloudstate-kotlin-support/0.5.1' to Maven Central: HTTP/1.1 403 Forbidden [message:In order to sync to Maven Central your package must be included in the JCenter repository]
```

**Comment by sleipnir** [comment]
@pvlugter Any ideas on what may be causing the error?

**Comment by jamesward** [comment]
Not sure if it is related but note that `0.5.1` already exists and can't be overwritten.

**Comment by sleipnir** [comment]
@jamesward Actually it doesn't seem to have anything to do with it, however I created a new 0.5.2 tag to avoid confusion with 0.5.1

**Comment by pvlugter** [comment]
As mentioned in #45:

> Sync to maven central via bintray can't be set up properly until there's a published version. So we'll need to tag and release `0.5.2` first, set up the jcenter linking, and then should be good to go from then on.

Once the first version is published to bintray, we can link to jcenter and sync to maven central. Should then work fine for subsequent releases.

**Comment by pvlugter** [comment]
`0.5.2` is linked to jcenter and synced to maven central. Should publish automatically from now on.

**Comment by sleipnir** [comment]
Thanks @pvlugter

**Comment by jamesward** [comment]
Thanks! Confirmed that everything is working with `0.5.2`
