### ISSUE TITLE
Move the tck shopping-cart docker image to a cloudstate owned repository

### ISSUE THREAD

**Issue by sleipnir** [cloudstateio/kotlin-support#9]
Currently, the main cloudstate tck will run the kotlin tck image on an external dockerhub repo.

**Comment by sleipnir** [comment]
ping @viktorklang

**Comment by viktorklang** [comment]
@sleipnir I think we should turn that around and have the TCK run on each language support build instead of the Cloudstate build itself. /cc @jroper

**Comment by sleipnir** [comment]
Yes. That would be nice, the point is that it may be necessary to change the TCK implementation itself so that user support doesn’t need Scala and Sbt dependencies, not that I don’t like those, but it wouldn’t make much sense to have them on projects based on other stacks like Go, C#, etc.

**Comment by viktorklang** [comment]
@sleipnir We should look into creating a native-image of the TCK so the user only needs to invoke it with the right parameters/config.

**Comment by sleipnir** [comment]
Cool

**Comment by sleipnir** [comment]
Related issue in Cloudstate repository is https://github.com/cloudstateio/cloudstate/issues/216

**Comment by sleipnir** [comment]
Kotlin docker hub links
https://hub.docker.com/r/cloudstateio/samples-kotlin-chat
https://hub.docker.com/r/cloudstateio/samples-kotlin-pingpong
https://hub.docker.com/r/cloudstateio/samples-kotlin-shopping-cart
